### ISSUE TITLE
Preview sometimes not loading correctly

### ISSUE THREAD

**Issue by shirnschall** [ReeSilva/cerebro-vagalume-plugin#4]
As you can see in the image sometimes the preview does not load. After pressing backspace a few times and trying some other keys it usually begins to load the preview. Sometimes the preview works and sometimes it does not. When it is working it sometimes stops working the next time I open the search bar. 
![cerebro](https://cloud.githubusercontent.com/assets/11620061/24922150/8975c654-1eed-11e7-8aca-693cb3431951.png)

**Comment by shirnschall** [comment]
sorry for posting this in the wrong repository...

**Comment by ReeSilva** [comment]
@hirnschallsebastian Don't worry, man, mistakes happen :)
